### ISSUE TITLE
Не видит хедер storage_engine.h

### ISSUE THREAD

**Issue by LuckThemAll** [roflan-da/roflandb#20]
Шо делать если при попытке заинклудить storage_engine.h в файле с тестами он не видит такого файла, приходится прописывать относительный путь до него, но тогда он не цепляет cpp файл, можешь переключиться на 15 ветку и попробовать заинклудить, наверн где то что то не прописано в CMake

**Comment by ZeroICQ** [comment]
смерджил твою ветку с dev. Там есть тест, который крашит. Найди и закомменть, как временное решение.
