### ISSUE TITLE
Парсинг базового DDL

### ISSUE THREAD

**Issue by ZeroICQ** [roflan-da/roflandb#5]
Bison parser + Flex Lexer

- [x] CREATE TABLE
- [ ] DROP TABLE
- [x] SHOW CREATE TABLE NAME
- [x] Парсер должен принимать на вход строку. Возвращать класс Command
---
http://gnuwin32.sourceforge.net/packages/bison.htm
http://gnuwin32.sourceforge.net/packages/flex.htm
если будут проблемы с компиляций windows версий, тогда рабочий вариант - под виртулкой сделать общую папку с проектом и компилить там.
Ну или просто использовать линукс.

Документация по лексеру флексу
http://westes.github.io/flex/manual/
Самая важная часть
http://westes.github.io/flex/manual/Patterns.html#Patterns

за флекс отвечает файл scanner.ll

Документация по бизону:
https://www.gnu.org/software/bison/manual/
за бизон отвечает файл parser.yy

За их взаимодействие отвечает класс Driver.

Вручную можно редачить файлы:
scanner.ll
parser.yy
driver.h
driver.cpp
Остальные, ради своей же безопасности, лучше не открывать.

После внесения изменений используй команды:
```flex scanner.ll```
```bison parser.yy```

Пример, как это работает вместе
https://github.com/bingmann/flex-bison-cpp-example

В классе driver делаешь поле, например result (придумай более осмысленное название) и в парсере создаёшь команду и присваиваешь её в это поле. Тут надо быть очень аккуратным с указателями, чтобы не было утечек.

**Comment by LuckThemAll** [comment]
https://stackoverflow.com/questions/26619079/compiling-flex-and-bison-into-cpp

**Comment by boriswinner** [comment]
https://epaperpress.com/lexandyacc/download/LexAndYaccTutorial.pdf
гайд Lex + Yacc

**Comment by boriswinner** [comment]
ещё кокойта туториал
http://rus-linux.net/lib.php?name=/MyLDP/algol/lex-yacc-howto.html
