### ISSUE TITLE
Фиксы и улучшения сторедж енджина

### ISSUE THREAD

**Issue by SergeyZinkovich** [roflan-da/roflandb#51]
- [x] size_t в циклах
- [ ] конструктор таблицы в приват
- [ ] использовать get_table в других методах
- [ ] в get_table делать что то в случае, когда такой таблицы не существует
- [ ] при создании таблицы проверять, что такой нет
- [ ] сделать что то для эффективного нахождения колонок
- [ ] разделить на модули

**Comment by LuckThemAll** [comment]
убрал "проверка на существование в инсерте и селекте" так как валидность проверяется перед обращением к storage_engine во время execute;
